
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "home-vn"
    label: "Home"
    folder: "src/data/home"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Menu", name: "menu", widget: "list" }
      - name: "slide"
        label: "Slide"
        widget: "object"
        fields:
          - { label: "Image 1",name: "slide-img1",widget: "image"}
          - { label: " Caption 1 ", name: "slide-caption1", widget: "string" } 
          - { label: " Details", name: "slide-detail1", widget: "list" }
          - { label: " Image 2",name: "thumbnail2",widget: "image"}
          - { label: " Caption 2", name: "slide-caption2", widget: "string" } 
          - { label: " Details", name: "slide-detail2", widget: "list" }
          - { label: " Image 3",name: "thumbnail3",widget: "image"}
          - { label: " Caption 3", name: "slide-caption3", widget: "string" } 
          - { label: " Details", name: "slide-detail3", widget: "list" }
          - { label: " Image 4",name: "thumbnail4",widget: "image"}
          - { label: " Caption 4", name: "slide-caption4", widget: "string" } 
          - { label: " Details", name: "slide-detail4", widget: "list" }
      - { label: "Lead text", name: "lead", widget: "string" }
      - name: "home-service"
        label: "Home -- Service"
        widget: "object"
        fields:
          - { label: "Title",name: "home-service-title",widget: "string"}
          - { label: "Description",name: "home-service-des",widget: "string"}
          - name: "service1"
            label: "Service1"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-box-title",widget: "string"}
              - { label: "Description",name: "home-box-desc",widget: "string"}
              - { label: "Icon",name: "home-boxe-icon",widget: "string"}
          - name: "service2"
            label: "Service2"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-box-title",widget: "string"}
              - { label: "Description",name: "home-box-desc",widget: "string"}
              - { label: "Icon",name: "home-boxe-icon",widget: "string"}
          - name: "service3"
            label: "Service3"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-box-title",widget: "string"}
              - { label: "Description",name: "home-box-desc",widget: "string"}
              - { label: "Icon",name: "home-boxe-icon",widget: "string"}
      - name: "home-about"
        label: "Home -- About"
        widget: "object"
        fields:
          - { label: "Title",name: "home-about-title",widget: "string"}
          - { label: "Description",name: "home-about-des",widget: "string"}
          - name: "panel1"
            label: "About Panel 1"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-box-title",widget: "string"}
              - { label: "Description",name: "home-box-desc",widget: "string"}
              - { label: "Icon",name: "home-boxe-icon",widget: "string"}
          - name: "panel2"
            label: "About Panel 2"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-box-title",widget: "string"}
              - { label: "Description",name: "home-box-desc",widget: "string"}
              - { label: "Icon",name: "home-boxe-icon",widget: "string"}
          - name: "panel3"
            label: "About Panel 3"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-box-title",widget: "string"}
              - { label: "Description",name: "home-box-desc",widget: "string"}
              - { label: "Icon",name: "home-boxe-icon",widget: "string"}


