
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "home-vn"
    label: "Home"
    folder: "src/data/home"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - name: "slide"
        label: "Slide"
        widget: "object"
        fields:
          - { label: "Slide Image 1",name: "thumbnail1",widget: "image"}
          - { label: "Slide Caption 1 ", name: "slide-caption1", widget: "string" } 
          - { label: "Slide Details", name: "slide-detail1", widget: "list" }
          - { label: "Slide Image 2",name: "thumbnail2",widget: "image"}
          - { label: "Slide Caption 2", name: "slide-caption2", widget: "string" } 
          - { label: "Slide Details", name: "slide-detail2", widget: "list" }
          - { label: "Slide Image 3",name: "thumbnail3",widget: "image"}
          - { label: "Slide Caption 3", name: "slide-caption3", widget: "string" } 
          - { label: "Slide Details", name: "slide-detail3", widget: "list" }
          - { label: "Slide Image 4",name: "thumbnail4",widget: "image"}
          - { label: "Slide Caption 4", name: "slide-caption4", widget: "string" } 
          - { label: "Slide Details", name: "slide-detail4", widget: "list" }

