

backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:       
#  HOME vietnamese
  - name: "home-vn"
    label: "Home - Tiếng Việt"
    folder: "src/data/vi/home"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Tiêu đề", name: "title-vn", widget: "string" }
      - { label: "Publish Date", name: "date-vn", widget: "datetime" }
      - { label: "Menu", name: "menu-vn", widget: "list" }
      - name: "slide-vn"
        label: "Slide"
        widget: "object"
        fields:
          - { label: "Ảnh Slide 1",name: "slide-img1-vn",widget: "image"}
          - { label: " Caption Slide 1 ", name: "slide-caption1-vn", widget: "string" } 
          - { label: " Details Slide 1", name: "slide-detail1-vn", widget: "list" }
          - { label: " Ảnh Slide 2",name: "slide-img2-vn",widget: "image"}
          - { label: " Caption Slide 2", name: "slide-caption2-vn", widget: "string" } 
          - { label: " Details Slide 2", name: "slide-detail2-vn", widget: "list" }
          - { label: " Ảnh Slide 3",name: "slide-img3-vn",widget: "image"}
          - { label: " Caption Slide 3", name: "slide-caption3-vn", widget: "string" } 
          - { label: " Details Slide 3", name: "slide-detail3-vn", widget: "list" }
      - { label: "Lead text", name: "lead-vn", widget: "string" }
      - name: "home-1st-vn"
        label: "Home -- Nội dung 1"
        widget: "object"
        fields:
          - { label: "Tiêu đề",name: "home-1st-title-vn",widget: "string"}
          - { label: "Miêu tả",name: "home-1st-des-vn",widget: "string"}
          - name: "home-1st-vn-1"
            label: "Box 1"
            widget: "object"
            fields: 
              - { label: "Tiêu đề",name: "home-box-title-vn-1",widget: "string"}
              - { label: "Miêu tả",name: "home-box-desc-vn-1",widget: "string"}
          - name: "home-1st-vn-2"
            label: "Box 2"
            widget: "object"
            fields: 
              - { label: "Tiêu đề",name: "home-box-title-vn-2",widget: "string"}
              - { label: "Miêu tả",name: "home-box-desc-vn-2",widget: "string"}
          - name: "home-1st-vn-3"
            label: "Box 3"
            widget: "object"
            fields: 
              - { label: "Tiêu đề",name: "home-box-title-vn-3",widget: "string"}
              - { label: "Miêu tả",name: "home-box-desc-vn-3",widget: "string"}
      - name: "home-2nd-vn"
        label: "Home -- Nội dung 2"
        widget: "object"
        fields:
          - { label: "Tiêu đề",name: "home-2nd-title-vn",widget: "string"}
          - { label: "Miêu tả",name: "home-2nd-desc-vn",widget: "string"}
          - name: "panel-vn-1"
            label: "About Panel 1"
            widget: "object"
            fields: 
              - { label: "Tiêu đề",name: "home-panel-title-vn-1",widget: "string"}
              - { label: "Miêu tả",name: "home-panel-desc-vn-1",widget: "string"}
          - name: "panel-vn-2"
            label: "About Panel 2"
            widget: "object"
            fields: 
              - { label: "Tiêu đề",name: "home-panel-title-vn-2",widget: "string"}
              - { label: "Miêu tả",name: "home-panel-desc-vn-2",widget: "string"}
          - name: "panel-vn-3"
            label: "About Panel 3"
            widget: "object"
            fields: 
              - { label: "Tiêu đề",name: "home-panel-title-vn-3",widget: "string"}
              - { label: "Miêu tả",name: "home-panel-desc-vn-3",widget:  "string"}
          - name: "panel-vn-4"
            label: "About Panel 4"
            widget: "object"
            fields: 
              - { label: "Tiêu đề",name: "home-panel-title-vn-4",widget: "string"}
              - { label: "Miêu tả",name: "home-panel-desc-vn-4",widget:  "string"}
          - name: "about-paragraph-vn"
            label: "Đoạn văn giới thiệu"
            widget: "object"
            fields: 
              - { label: "Tiêu đề",name: "about-paragraph-title-vn",widget: "string"}
              - { label: "Đoạn 1 ",name: "about-paragraph-vn-1",widget: "string"}
              - { label: "Đoạn 2 ",name: "about-paragraph-vn-2",widget: "string"}
              - { label: "Ảnh",name: "about-img" ,widget: "image"}
      - name: "home-banner-vn"
        label: "Home -- Banner"
        widget: "object"
        fields:
          - { label: "Heading",name: "home-banner-heading-vn",widget: "string"}
          - { label: "Miêu tả",name: "home-banner-desc-vn",widget: "string"}
          - { label: "Ảnh",name: "banner-img-vn" ,widget: "image"}   
      - name: "home-3rd-vn"
        label: "Home -- Nội dung 3"
        widget: "object"
        fields:
          - { label: "Tiêu đề",name: "home-3rd-title-vn",widget: "string"}
          - { label: "Miêu tả",name: "home-3rd-desc-vn",widget: "string"}
          - name: "tab1-vn"
            label: "Tab 1"
            widget: "object"
            fields:
              - { label: "Tiêu đề",name: "tab-title-vn-1",widget: "string"}  
              - { label: "Miêu tả",name: "tab-desc-vn-1",widget: "string"}  
              - { label: "Ảnh",name: "tab-img-vn-1",widget: "image"}  
          - name: "tab2-vn"
            label: "Tab 2"
            widget: "object"
            fields:
              - { label: "Tiêu đề",name: "tab-title-vn-2",widget: "string"}  
              - { label: "Miêu tả",name: "tab-desc-vn-2",widget: "string"}  
              - { label: "Ảnh",name: "tab-img-vn-2",widget: "image"}  
          - name: "tab3-vn"
            label: "Tab 3"
            widget: "object"
            fields:
              - { label: "Tiêu đề",name: "tab-title-vn-3",widget: "string"}  
              - { label: "Miêu tả",name: "tab-desc-vn-3",widget: "string"}  
              - { label: "Ảnh",name: "tab-img-vn-3",widget: "image"}  
          - name: "tab4-vn"
            label: "Tab 4"
            widget: "object"
            fields:
              - { label: "Tiêu đề",name: "tab-title-vn-4",widget: "string"}  
              - { label: "Miêu tả",name: "tab-desc-vn-4",widget: "string"}  
              - { label: "Ảnh",name: "tab-img-vn-4",widget: "image"}  
  
  - name: "home-en"
    label: "Home - English"
    folder: "src/data/en/home"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title-en", widget: "string" }
      - { label: "Publish Date", name: "date-en", widget: "datetime" }
      - { label: "Menu", name: "menu-en", widget: "list" }
      - name: "slide-en"
        label: "Slide"
        widget: "object"
        fields:
          - { label: "Image Slide 1",name: "slide-img1-en",widget: "image"}
          - { label: " Caption Slide 1 ", name: "slide-caption1-en", widget: "string" } 
          - { label: " Details Slide 1", name: "slide-detail1-en", widget: "list" }
          - { label: " Image Slide 2",name: "slide-img2-en",widget: "image"}
          - { label: " Caption Slide 2", name: "slide-caption2-en", widget: "string" } 
          - { label: " Details Slide 2", name: "slide-detail2-en", widget: "list" }
          - { label: " Image Slide 3",name: "slide-img3-en",widget: "image"}
          - { label: " Caption Slide 3", name: "slide-caption3-en", widget: "string" } 
          - { label: " Details Slide 3", name: "slide-detail3-en", widget: "list" }
      - { label: "Lead text", name: "lead-en", widget: "string" }
      - name: "home-1st-en"
        label: "Home -- Content 1"
        widget: "object"
        fields:
          - { label: "Title",name: "home-1st-title-en",widget: "string"}
          - { label: "Description",name: "home-1st-des-en",widget: "string"}
          - name: "home-1st-en-1"
            label: "Box 1"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-box-title-en-1",widget: "string"}
              - { label: "Description",name: "home-box-desc-en-1",widget: "string"}
          - name: "home-1st-en-2"
            label: "Box 2"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-box-title-en-2",widget: "string"}
              - { label: "Description",name: "home-box-desc-en-2",widget: "string"}
          - name: "home-1st-en-3"
            label: "Box 3"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-box-title-en-3",widget: "string"}
              - { label: "Description",name: "home-box-desc-en-3",widget: "string"}
      - name: "home-2nd-en"
        label: "Home -- Content 2"
        widget: "object"
        fields:
          - { label: "Title",name: "home-2nd-title-en",widget: "string"}
          - { label: "Description",name: "home-2nd-desc-en",widget: "string"}
          - name: "panel-en-1"
            label: "About Panel 1"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-panel-title-en-1",widget: "string"}
              - { label: "Description",name: "home-panel-desc-en-1",widget: "string"}
          - name: "panel-en-2"
            label: "About Panel 2"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-panel-title-en-2",widget: "string"}
              - { label: "MDescription",name: "home-panel-desc-en-2",widget: "string"}
          - name: "panel-en-3"
            label: "About Panel 3"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-panel-title-en-3",widget: "string"}
              - { label: "Description",name: "home-panel-desc-en-3",widget:  "string"}
          - name: "panel-en-4"
            label: "About Panel 4"
            widget: "object"
            fields: 
              - { label: "Title",name: "home-panel-title-en-4",widget: "string"}
              - { label: "Description",name: "home-panel-desc-en-4",widget:  "string"}
          - name: "about-paragraph-en"
            label: "About Paragraph"
            widget: "object"
            fields: 
              - { label: "Title",name: "about-paragraph-title-en",widget: "string"}
              - { label: "Part 1 ",name: "about-paragraph-en-1",widget: "string"}
              - { label: "Part 2 ",name: "about-paragraph-en-2",widget: "string"}
              - { label: "Image",name: "about-img" ,widget: "image"}
      - name: "home-banner-en"
        label: "Home -- Banner"
        widget: "object"
        fields:
          - { label: "Heading",name: "home-banner-heading-en",widget: "string"}
          - { label: "Description",name: "home-banner-desc-en",widget: "string"}
          - { label: "Image",name: "banner-img-en" ,widget: "image"}   
      - name: "home-3rd-en"
        label: "Home -- Content 3"
        widget: "object"
        fields:
          - { label: "Title",name: "home-3rd-title-en",widget: "string"}
          - { label: "Description",name: "home-3rd-desc-en",widget: "string"}
          - name: "tab1-en"
            label: "Tab 1"
            widget: "object"
            fields:
              - { label: "Title",name: "tab-title-en-1",widget: "string"}  
              - { label: "Description",name: "tab-desc-en-1",widget: "string"}  
              - { label: "Image",name: "tab-img-en-1",widget: "image"}  
          - name: "tab2-en"
            label: "Tab 2"
            widget: "object"
            fields:
              - { label: "Title",name: "tab-title-en-2",widget: "string"}  
              - { label: "Description",name: "tab-desc-en-2",widget: "string"}  
              - { label: "Image",name: "tab-img-en-2",widget: "image"}  
          - name: "tab3-en"
            label: "Tab 3"
            widget: "object"
            fields:
              - { label: "Title",name: "tab-title-en-3",widget: "string"}  
              - { label: "Description",name: "tab-desc-en-3",widget: "string"}  
              - { label: "Image",name: "tab-img-en-3",widget: "image"}  
          - name: "tab4-en"
            label: "Tab 4"
            widget: "object"
            fields:
              - { label: "Title",name: "tab-title-en-4",widget: "string"}  
              - { label: "Description",name: "tab-desc-en-4",widget: "string"}  
              - { label: "Image",name: "tab-img-en-4",widget: "image"}  
  

#Services page
  - name: "services-vn"
    label: "Services- Tiếng Việt"
    folder: "src/data/vi/services"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
    preview: false
    fields:
      - { label: "Tiêu đề", name: "title-vn", widget: "string" }
      - { label: "Publish Date", name: "date-vn", widget: "datetime" }      
      - name: "banner-vn"
        label: "Banner"
        widget: "object"
        fields:
          - { label: "Ảnh nền Banner",name: "banner-img-vn",widget: "image"}
          - { label: " Tiêu đề banner", name: "banner-title-vn", widget: "string" } 
          - { label: " Lời dẫn banner", name: "banner-lead-vn", widget: "string" }         
    
      - name: "services-1st-vn"
        label: "Service-- Nội dung 1"
        widget: "object"
        fields:
          - {label: "Tiêu đề",name: "service-1st-title-vn",widget: "string"}         
          - name: "list-card-1"
            label: "list-card 1 "
            widget: "object"
            fields:               
              - { label: "Ảnh của card",name: "img-card",widget: "image"}
              - { label: "Tiêu đề",name: "title-vn",widget: "string"}
              - { label: "Miêu tả",name: "lead-vn",widget: "string"}
        
     
  
          